export const SAVE_NEW_TRANSACTION = 'SAVE_NEW_TRANSACTION';
export const SAVING_NEW_TRANSACTIONS_FAILED = 'SAVING_NEW_TRANSACTIONS_FAILED';
export const SAVING_NEW_TRANSACTIONS_COMPLETE =
  'SAVING_NEW_TRANSACTIONS_COMPLETE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const FETCHING_TRANSACTIONS = 'FETCHING_TRANSACTIONS';
export const FETCHING_TRANSACTIONS_COMPLETE = 'FETCHING_TRANSACTIONS_COMPLETE';
export const FETCHING_TRANSACTIONS_FAILED = 'FETCHING_TRANSACTIONS_FAILED';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const DELETE_TRANSACTION_FAILED = 'DELETE_TRANSACTION';
export const DELETE_TRANSACTION_COMPLETE = 'DELETE_TRANSACTION_COMPLETE';
